# Generated by Django 5.0.7 on 2024-08-02 09:04

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('director', models.TextField(max_length=100)),
                ('review_content', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('reviewer_email_id', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Non Published', 'Non Published')], max_length=20)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('SciFi', 'SciFi'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller')], max_length=35)),
            ],
        ),
    ]
