# Generated by Django 5.0.7 on 2024-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
